-- Generated static seed.sql for DSS Sports Inter-House Meet
-- Upsert-safe SQL file runnable directly in Supabase SQL editor or psql
BEGIN;

-- 1. HOUSES
INSERT INTO public.houses (id, name, color_hex, short_code) VALUES ('65b29d6e-2573-563b-afef-482244e8348e', 'Karnali', '#A16207', 'KAR') ON CONFLICT (name) DO UPDATE SET color_hex = EXCLUDED.color_hex, short_code = EXCLUDED.short_code;
INSERT INTO public.houses (id, name, color_hex, short_code) VALUES ('ec04892e-017b-5ff3-a9ca-bb093946d2fb', 'Koshi', '#5E7891', 'KOS') ON CONFLICT (name) DO UPDATE SET color_hex = EXCLUDED.color_hex, short_code = EXCLUDED.short_code;
INSERT INTO public.houses (id, name, color_hex, short_code) VALUES ('fdb4c0e5-c23d-5e7d-9c29-15a536c28491', 'Mahakali', '#A5534B', 'MAH') ON CONFLICT (name) DO UPDATE SET color_hex = EXCLUDED.color_hex, short_code = EXCLUDED.short_code;
INSERT INTO public.houses (id, name, color_hex, short_code) VALUES ('06e07dea-3330-57e0-b8f4-355a5c9d1cbd', 'Mechi', '#7B843F', 'MEC') ON CONFLICT (name) DO UPDATE SET color_hex = EXCLUDED.color_hex, short_code = EXCLUDED.short_code;

-- 2. SPORTS
INSERT INTO public.sports (id, name, type, level) VALUES ('4a84bfea-d954-5d9d-be7e-6a4eb381c388', 'Futsal', 'football', 'HS') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, level = EXCLUDED.level;
INSERT INTO public.sports (id, name, type, level) VALUES ('0017d484-f403-5b72-a905-71b2f8af6eb4', 'Basketball', 'basketball', 'HS') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, level = EXCLUDED.level;
INSERT INTO public.sports (id, name, type, level) VALUES ('e500d4e8-503b-560d-bee0-1e9b4fe76ee9', 'Cricksal', 'generic', 'HS') ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, level = EXCLUDED.level;

-- 3. TOURNAMENT GROUPS
INSERT INTO public.tournament_groups (id, sport_id, gender, format, point_win, point_draw, point_loss) SELECT '6c36da52-823a-59f6-9f0d-3d51574fdde0', s.id, 'Boys', 'pool_to_semis', 3, 1, 0 FROM public.sports s WHERE s.name = 'Futsal' ON CONFLICT (sport_id, gender) DO UPDATE SET format = EXCLUDED.format;
INSERT INTO public.tournament_groups (id, sport_id, gender, format, point_win, point_draw, point_loss) SELECT '232ebb3e-cd55-5d8e-85f6-fdaa130171a0', s.id, 'Girls', 'round_robin', 3, 1, 0 FROM public.sports s WHERE s.name = 'Futsal' ON CONFLICT (sport_id, gender) DO UPDATE SET format = EXCLUDED.format;
INSERT INTO public.tournament_groups (id, sport_id, gender, format, point_win, point_draw, point_loss) SELECT '6ce5e226-91a6-5b7a-9acf-0851572177cc', s.id, 'Boys', 'round_robin', 3, 1, 0 FROM public.sports s WHERE s.name = 'Basketball' ON CONFLICT (sport_id, gender) DO UPDATE SET format = EXCLUDED.format;
INSERT INTO public.tournament_groups (id, sport_id, gender, format, point_win, point_draw, point_loss) SELECT '7bfdc653-73ca-5d99-b1d2-d262e5d2c020', s.id, 'Girls', 'round_robin', 3, 1, 0 FROM public.sports s WHERE s.name = 'Basketball' ON CONFLICT (sport_id, gender) DO UPDATE SET format = EXCLUDED.format;
INSERT INTO public.tournament_groups (id, sport_id, gender, format, point_win, point_draw, point_loss) SELECT '7aba6048-c70c-5803-9446-fc29d17ef870', s.id, 'Boys', 'pool_to_semis', 3, 1, 0 FROM public.sports s WHERE s.name = 'Cricksal' ON CONFLICT (sport_id, gender) DO UPDATE SET format = EXCLUDED.format;
INSERT INTO public.tournament_groups (id, sport_id, gender, format, point_win, point_draw, point_loss) SELECT 'b7bbf4bd-3db5-55b4-8a93-ddadbbe07950', s.id, 'Girls', 'round_robin', 3, 1, 0 FROM public.sports s WHERE s.name = 'Cricksal' ON CONFLICT (sport_id, gender) DO UPDATE SET format = EXCLUDED.format;

-- 4. TEAMS / SQUADS
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '7a6fe2c7-fd8a-5ef3-ad7f-4744c3754b90', 'Karnali A', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Karnali' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT 'db3a0910-92d1-56d2-858d-4774d1962232', 'Karnali B', h.id, 'Boys', 'B', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Karnali' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT 'a89423b7-5025-539f-8c29-3d3d29fd3433', 'Karnali A', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Karnali' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '93c67025-7d74-595c-9c5f-3f473f11abc6', 'Karnali B', h.id, 'Girls', 'B', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Karnali' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '18dac477-9872-57ce-8999-b22ad5d6abfc', 'Karnali A', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Karnali' AND s.name = 'Basketball' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '01d1df3a-065d-535a-b022-ca687a5482f8', 'Karnali B', h.id, 'Boys', 'B', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Karnali' AND s.name = 'Basketball' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT 'c636d11f-0c51-5ec5-9cbd-9081dc99053b', 'Karnali A', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Karnali' AND s.name = 'Basketball' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '90450280-0a85-51fe-8072-4746a0976ae6', 'Karnali B', h.id, 'Girls', 'B', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Karnali' AND s.name = 'Basketball' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '47faa74c-5096-5dd5-b216-1bb1f8dd86fc', 'Karnali A', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Karnali' AND s.name = 'Cricksal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '4dc9d67f-e89e-5052-82d2-f9863091809d', 'Karnali B', h.id, 'Boys', 'B', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Karnali' AND s.name = 'Cricksal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '2d3abda1-96d8-5e59-83b6-82facae7296f', 'Karnali', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Karnali' AND s.name = 'Cricksal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '828fb1be-1cff-570e-87b7-c53d4a5acdab', 'Koshi A', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Koshi' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '5ee78ead-d972-5393-9771-b7985d254e40', 'Koshi B', h.id, 'Boys', 'B', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Koshi' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '467106e1-df8a-5ecb-9c3b-f67b90ca59ed', 'Koshi', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Koshi' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '5ac656ca-1485-5cc1-a86b-9856225b60cc', 'Koshi', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Koshi' AND s.name = 'Basketball' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT 'd4e77187-e1c5-529b-8831-a15bbe94db0d', 'Koshi', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Koshi' AND s.name = 'Basketball' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '20d80092-4b2e-5cb6-ad9d-08a049e51fe2', 'Koshi A', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Koshi' AND s.name = 'Cricksal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '6e9d9572-9f5b-5cbc-990e-3eafaf2456a6', 'Koshi B', h.id, 'Boys', 'B', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Koshi' AND s.name = 'Cricksal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '2c3ce6b2-8905-5859-bed3-784874953106', 'Koshi', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Koshi' AND s.name = 'Cricksal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT 'f030642b-682a-5d9b-a392-e5060a08b69f', 'Mahakali', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mahakali' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT 'e752c9de-7a1e-5fac-a988-182aa1bf91ef', 'Mahakali', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mahakali' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '9e089f8a-4ba4-55a0-a695-fc6636554369', 'Mahakali', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mahakali' AND s.name = 'Basketball' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT 'f32e5d64-5dd6-5d5a-8068-3cfc580b4bd7', 'Mahakali', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mahakali' AND s.name = 'Basketball' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT 'ae982636-f432-5151-804b-711a05cf7538', 'Mahakali', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mahakali' AND s.name = 'Cricksal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '897372a7-5755-5a4d-8542-23751ce11f6a', 'Mahakali', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mahakali' AND s.name = 'Cricksal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '25498cfe-2761-53bd-85ba-f17d036c334b', 'Mechi A', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mechi' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '6201f59d-5978-5361-8fbc-dbd15e371f69', 'Mechi B', h.id, 'Boys', 'B', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mechi' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '53af68c2-8030-58dd-861d-3b765e4d13c9', 'Mechi', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mechi' AND s.name = 'Futsal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '1e578560-2532-55f1-9585-77e01ec741fb', 'Mechi', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mechi' AND s.name = 'Basketball' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '288ffd61-14f6-5bb9-9e6e-db16ab0b65be', 'Mechi', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mechi' AND s.name = 'Basketball' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '5e370f55-f7f6-5f79-a229-90afa9a9a610', 'Mechi A', h.id, 'Boys', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mechi' AND s.name = 'Cricksal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '117c8df2-9a3b-5ab4-b05b-2dbb7359d412', 'Mechi B', h.id, 'Boys', 'B', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mechi' AND s.name = 'Cricksal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;
INSERT INTO public.teams (id, name, house_id, gender, squad_label, pool, sport_id, level) SELECT '79b1f2cf-5eaf-5759-9ddf-bd004b16f9c4', 'Mechi', h.id, 'Girls', 'A', NULL, s.id, 'HS' FROM public.houses h CROSS JOIN public.sports s WHERE h.name = 'Mechi' AND s.name = 'Cricksal' ON CONFLICT (house_id, sport_id, gender, squad_label, level) DO UPDATE SET pool = EXCLUDED.pool, name = EXCLUDED.name;

-- 5. PLAYERS

-- 6. MATCHES

COMMIT;
